# Development environment values
namespace: d6af69-prod
replicaCount: 2

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

route:
  enabled: true
  host: buildingcode.gov.bc.ca
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    secretName: buildingcode-route-tls

autoscaling:
  enabled: false
